export * from './internal/generated/passes.generated.js';
import type { ModulePass, OptimizeOptions } from './internal/generated/passes.generated.js';
import type { StarshineResult } from './internal/shared.js';
import type { Module } from './lib.js';

export function modulePass(name: string): ModulePass;
export function optimizeModuleWithOptionsTrace(
  arg0: Module,
  arg1: Array<ModulePass>,
  arg2: OptimizeOptions,
  trace?: (msg: string) => void,
  tracePassDetails?: boolean,
  traceModuleStats?: boolean,
): StarshineResult<Module, string>;
export function alignmentLowering(): ModulePass;
export function avoidReinterprets(): ModulePass;
export function coalesceLocals(): ModulePass;
export function codeFolding(): ModulePass;
export function codePushing(): ModulePass;
export function constHoisting(): ModulePass;
export function constantFieldPropagation(): ModulePass;
export function dataflowOptimization(): ModulePass;
export function deadCodeElimination(): ModulePass;
export function deadArgumentElimination(): ModulePass;
export function deadArgumentEliminationOptimizing(): ModulePass;
export function signaturePruning(): ModulePass;
export function signatureRefining(): ModulePass;
export function duplicateImportElimination(): ModulePass;
export function globalRefining(): ModulePass;
export function globalStructInference(): ModulePass;
export function globalStructInferenceDescCast(): ModulePass;
export function globalTypeOptimization(): ModulePass;
export function simplifyGlobals(): ModulePass;
export function simplifyGlobalsOptimizing(): ModulePass;
export function globalEffects(): ModulePass;
export function propagateGlobalsGlobally(): ModulePass;
export function typeRefining(): ModulePass;
export function typeGeneralizing(): ModulePass;
export function typeFinalizing(): ModulePass;
export function typeUnFinalizing(): ModulePass;
export function unsubtyping(): ModulePass;
export function heap2local(): ModulePass;
export function heapStoreOptimization(): ModulePass;
export function inlining(): ModulePass;
export function inliningOptimizing(): ModulePass;
export function inlineMain(): ModulePass;
export function localCse(): ModulePass;
export function localSubtyping(): ModulePass;
export function loopInvariantCodeMotion(): ModulePass;
export function mergeLocals(): ModulePass;
export function mergeSimilarFunctions(): ModulePass;
export function mergeBlocks(): ModulePass;
export function flatten(): ModulePass;
export function reReloop(): ModulePass;
export function tupleOptimization(): ModulePass;
export function onceReduction(): ModulePass;
export function minimizeRecGroups(): ModulePass;
export function typeMerging(): ModulePass;
export function monomorphize(): ModulePass;
export function monomorphizeAlways(): ModulePass;
export function optimizeAddedConstants(): ModulePass;
export function optimizeAddedConstantsPropagate(): ModulePass;
export function optimizeInstructions(): ModulePass;
export function precompute(): ModulePass;
export function precomputePropagate(): ModulePass;
export function redundantSetElimination(): ModulePass;
export function pickLoadSigns(): ModulePass;
export function gufa(): ModulePass;
export function gufaOptimizing(): ModulePass;
export function gufaCastAll(): ModulePass;
export function i64ToI32Lowering(): ModulePass;
export function duplicateFunctionElimination(): ModulePass;
export function optimizeCasts(): ModulePass;
export function deNan(): ModulePass;
export function removeUnusedBrs(): ModulePass;
export function removeUnusedNames(): ModulePass;
export function simplifyLocals(): ModulePass;
export function simplifyLocalsNoTee(): ModulePass;
export function simplifyLocalsNoStructure(): ModulePass;
export function simplifyLocalsNoTeeNoStructure(): ModulePass;
export function simplifyLocalsNoNesting(): ModulePass;
export function untee(): ModulePass;
export function vacuum(): ModulePass;
export function reorderLocals(): ModulePass;
export function reorderTypes(): ModulePass;
export function reorderGlobals(): ModulePass;
export function reorderGlobalsAlways(): ModulePass;
export function reorderFunctions(): ModulePass;
export function reorderFunctionsByName(): ModulePass;
export function removeUnusedTypes(): ModulePass;
export function removeUnused(): ModulePass;
export function removeUnusedModuleElements(): ModulePass;
export function removeUnusedNonFunctionElements(): ModulePass;
export function directize(always?: boolean): ModulePass;
